name: "app1 - Build"
"on":
  push: {}
jobs:
  build:
    steps:
    - uses: "actions/checkout@v2"
      with:
        ref: "refs/heads/main"
    - run: "app1/.dash/build.sh"
    runs-on: "ubuntu-latest"
