name: "app2- Build"
"on":
  push:
    paths:
    - "x_app2/**"
jobs:
- steps:
  - uses: "actions/checkout@v2"
    with:
      ref:
        value: "refs/heads/main"
  - run: "x_app2/.dash/build.sh"
  runs-on: "ubuntu-latest"
