on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      username: hello

jobs:
  example_job:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
